apiVersion: apps/v1
kind: Deployment
metadata:
  name: pit2ny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pit2ny
  template:
    metadata:
      labels:
        app: pit2ny
    spec:
      containers:
        - name: pit2ny
          image: docker.io/praneethg34/demoflight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: pittsburgh
            - name: FROM_STATE
              value: pa
            - name: TO_CITY
              value: "new york"
            - name: TO_STATE
              value: ny
            - name: FLIGHT_NUMBER
              value: "PI2NY"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: da2la
spec:
  replicas: 1
  selector:
    matchLabels:
      app: da2la
  template:
    metadata:
      labels:
        app: da2la
    spec:
      containers:
        - name: da2la
          image: docker.io/praneethg34/demoflight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: dallas
            - name: FROM_STATE
              value: tx
            - name: TO_CITY
              value: "los angeles"
            - name: TO_STATE
              value: ca
            - name: FLIGHT_NUMBER
              value: "DA2LA"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bo2se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bo2se
  template:
    metadata:
      labels:
        app: bo2se
    spec:
      containers:
        - name: bo2se
          image: docker.io/praneethg34/demoflight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: boston
            - name: FROM_STATE
              value: ma
            - name: TO_CITY
              value: seattle
            - name: TO_STATE
              value: wa
            - name: FLIGHT_NUMBER
              value: "BO2SE"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci2bf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci2bf
  template:
    metadata:
      labels:
        app: ci2bf
    spec:
      containers:
        - name: ci2bf
          image: docker.io/praneethg34/demoflight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: cincinnati
            - name: FROM_STATE
              value: oh
            - name: TO_CITY
              value: buffalo
            - name: TO_STATE
              value: ny
            - name: FLIGHT_NUMBER
              value: "CI2BF"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2wi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: co2wy
  template:
    metadata:
      labels:
        app: co2wy
    spec:
      containers:
        - name: co2wy
          image: docker.io/praneethg34/demoflight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: columbus
            - name: FROM_STATE
              value: oh
            - name: TO_CITY
              value: wichita
            - name: TO_STATE
              value: ks
            - name: FLIGHT_NUMBER
              value: "CO2WY"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw2re
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nw2re
  template:
    metadata:
      labels:
        app: nw2re
    spec:
      containers:
        - name: nw2re
          image: docker.io/praneethg34/demoflight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: newark
            - name: FROM_STATE
              value: nj
            - name: TO_CITY
              value: reno
            - name: TO_STATE
              value: tx
            - name: FLIGHT_NUMBER
              value: "NW2RE"  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightupdater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightupdater
  template:
    metadata:
      labels:
        app: flightupdater
    spec:
      containers:
        - name: flightupdater
          image: docker.io/praneethg34/demoflightupdater:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: env
              value: production
         
