apiVersion: apps/v1
kind: Deployment
metadata:
  name: pit2ny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pit2ny
  template:
    metadata:
      labels:
        app: pit2ny
    spec:
      containers:
        - name: pit2ny
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: pittsburgh
            - name: FROM_STATE
              value: pa
            - name: TO_CITY
              value: "new york"
            - name: TO_STATE
              value: ny
            - name: FLIGHT_NUMBER
              value: "PI2NY"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: da2la
spec:
  replicas: 1
  selector:
    matchLabels:
      app: da2la
  template:
    metadata:
      labels:
        app: da2la
    spec:
      containers:
        - name: da2la
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: dallas
            - name: FROM_STATE
              value: tx
            - name: TO_CITY
              value: "los angeles"
            - name: TO_STATE
              value: ca
            - name: FLIGHT_NUMBER
              value: "DA2LA"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bo2se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bo2se
  template:
    metadata:
      labels:
        app: bo2se
    spec:
      containers:
        - name: bo2se
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: boston
            - name: FROM_STATE
              value: ma
            - name: TO_CITY
              value: seattle
            - name: TO_STATE
              value: wa
            - name: FLIGHT_NUMBER
              value: "BO2SE"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci2bf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci2bf
  template:
    metadata:
      labels:
        app: ci2bf
    spec:
      containers:
        - name: ci2bf
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: cincinnati
            - name: FROM_STATE
              value: oh
            - name: TO_CITY
              value: buffalo
            - name: TO_STATE
              value: ny
            - name: FLIGHT_NUMBER
              value: "CI2BF"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2wi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: co2wy
  template:
    metadata:
      labels:
        app: co2wy
    spec:
      containers:
        - name: co2wy
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: columbus
            - name: FROM_STATE
              value: oh
            - name: TO_CITY
              value: wichita
            - name: TO_STATE
              value: ks
            - name: FLIGHT_NUMBER
              value: "CO2WY"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw2re
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nw2re
  template:
    metadata:
      labels:
        app: nw2re
    spec:
      containers:
        - name: nw2re
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: newark
            - name: FROM_STATE
              value: nj
            - name: TO_CITY
              value: reno
            - name: TO_STATE
              value: tx
            - name: FLIGHT_NUMBER
              value: "NW2RE"  

---




apiVersion: apps/v1
kind: Deployment
metadata:
  name: chi2se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chi2se
  template:
    metadata:
      labels:
        app: chi2se
    spec:
      containers:
        - name: chi2se
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: chicago
            - name: FROM_STATE
              value: il
            - name: TO_CITY
              value: seattle
            - name: TO_STATE
              value: wa
            - name: FLIGHT_NUMBER
              value: "CHI2SE"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta2ba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ta2ba
  template:
    metadata:
      labels:
        app: ta2ba
    spec:
      containers:
        - name: ta2ba
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: tampa
            - name: FROM_STATE
              value: fl
            - name: TO_CITY
              value: baltimore
            - name: TO_STATE
              value: md
            - name: FLIGHT_NUMBER
              value: "ta2ba"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: de2or
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de2or
  template:
    metadata:
      labels:
        app: de2or
    spec:
      containers:
        - name: de2or
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: denver
            - name: FROM_STATE
              value: co
            - name: TO_CITY
              value: orlando
            - name: TO_STATE
              value: fl
            - name: FLIGHT_NUMBER
              value: "DE2OR"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: me2om
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me2om
  template:
    metadata:
      labels:
        app: me2om
    spec:
      containers:
        - name: me2om
          image: docker.io/praneethg34/demoflight:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: FROM_CITY
              value: memphis
            - name: FROM_STATE
              value: tn
            - name: TO_CITY
              value: omaha
            - name: TO_STATE
              value: ne
            - name: FLIGHT_NUMBER
              value: "ME2OM"  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightupdater
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flightupdater
  template:
    metadata:
      labels:
        app: flightupdater
    spec:
      containers:
        - name: flightupdater
          image: docker.io/praneethg34/demoflightupdater:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: env
              value: production
         
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightrouteupdater
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flightrouteupdater
  template:
    metadata:
      labels:
        app: flightrouteupdater
    spec:
      containers:
        - name: flightrouteupdater
          image: docker.io/praneethg34/demoflightrouteupdater:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: env
              value: production

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightapi
  template:
    metadata:
      labels:
        app: flightapi
    spec:
      containers:
        - name: flightapi
          image: docker.io/praneethg34/demoflightapi:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka1-kafka-bootstrap
            - name: env
              value: production


---

apiVersion: v1
kind: Service
metadata:
  name: flightapi
spec:
  selector:
    app: flightapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: ClusterIP